<?php

/**
 * @file
 * PHOK Platform: Client
 *
 */

/**
 * Implements hook_node_info().
 *
 * We use hook_node_info() to define our node content type.
 */
function phok_client_node_info() {
  return array(
    'client' => array(
      'name'        => t('Client'),
      'base'        => 'client',
      'description' => t('A <em>client</em> is an individual who utilizes the services of the organization.'),
      'help'        => t('A <em>client</em> is an individual who utilizes the services of the organization. It is important to enter this information as fully and completely as possible.'),
      'has_title'   => TRUE,
      'title_label' => t('Client Name'),
      'locked'      => TRUE, // Cannot change machine name
    ),
  );
}

/**
 * Implements hook_form().
 *
 * Drupal needs for us to provide a form that lets the user add content. You
 * can get fancy with this form, or you can just punt and return the default
 * form that node_content will provide.
 */
function phok_client_form($node, $form_state) {
  return node_content_form($node, $form_state);
}

/**
 * Define the field instances for our content type.
 *
 * @return array
 *   An associative array specifying the instances we wish to add to our new
 *   node type.
 */
/*function _phok_client_installed_instances() {
  return array(
    'phok_client_hiv_proof' => array(
      'field_name'  => 'phok_client_hiv_proof',
      'label'       => t('Proof of HIV+ Status'),
      'description' => t(''),
      'required'    => FALSE,
      //'settings'    => array(),
      'widget'      => array(
        'type'        => 'file_generic',
        //'settings'    => array(),
        'weight'      => 2.10,
      ),
      'display'     => array(
        'default'     => array(
          'label'     => 'hidden',
          //'type'      => 'file_default',
          //'settings'  => array(),
        ),
      ),
    ),
  );
}**/

/**
 * @} End of "defgroup phok_client".
 */
